---
# ===== SITE.YML - Master Playbook =====
# Este playbook ejecuta toda la configuracion del cluster SLURM

- name: "Paqueteria para que ansible funcione"
  hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Instalar sshpass para uso de Ansible con password
      apt:
        name: sshpass
        state: present
  import_playbook: playbooks/slurm-general.yml
  tags:
    - general

- name: "Configuracion Headnode"
  import_playbook: playbooks/slurm-headnode.yml
  tags:
    - headnode

- name: "Configuracion Workers"
  import_playbook: playbooks/slurm-workers.yml
  tags:
    - workers

- name: Resumen
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Display deployment summary
      debug:
        msg:
          - ""
          - "========================================="
          - "Cluster SLURM configurado"
          - "========================================="
          - ""