---
# ===== Monitoreo con Prometheus y Grafana =====

- name: Instalar Docker y dependencias de Python para Docker
  ansible.builtin.apt:
    name:
      - docker.io
      - python3-docker
    state: present
  tags: [install_docker]

- name: Crear estructura de directorios
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: 472
    group: root
    mode: '0755'
  loop:
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/dashboards
    - /etc/grafana/dashboards_json
    - /etc/prometheus
  tags: [create_directories]

- name: Provisionar archivos de configuración
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: 'grafana_datasource.yml.j2', dest: '/etc/grafana/provisioning/datasources/prometheus.yml' }
    - { src: 'grafana_dashboards.yml.j2', dest: '/etc/grafana/provisioning/dashboards/main.yaml' }
    - { src: 'prometheus.yml.j2', dest: '/etc/prometheus/prometheus.yml' }
  notify: Reiniciar contenedor prometheus
  tags: [monitoring_config]

- name: Descargar Dashboard Node Exporter Full (ID 1860)
  ansible.builtin.get_url:
    url: https://grafana.com/api/dashboards/1860/revisions/latest/download
    dest: /etc/grafana/dashboards_json/node-exporter-full.json
    mode: '0644'
  tags: [download_dashboard]

- name: Corregir el Data Source en el JSON del Dashboard
  ansible.builtin.replace:
    path: /etc/grafana/dashboards_json/node-exporter-full.json
    regexp: '\$\{DS_PROMETHEUS\}'
    replace: 'Prometheus'
  tags: [fix_dashboard]

# --- Despliegue con Módulos Nativos ---

- name: Desplegar Contenedor Prometheus
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus:latest
    state: started
    restart_policy: always
    network_mode: host
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  tags: [deploy_prometheus]

- name: Desplegar Contenedor Grafana
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: started
    restart_policy: always
    network_mode: host
    env:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - /etc/grafana/provisioning:/etc/grafana/provisioning
      - /etc/grafana/dashboards_json:/var/lib/grafana/dashboards
  tags: [deploy_grafana]
