---
# ===== SLURM Compute Daemon (slurmd) =====

- name: Asegurar directorio de configuración
  ansible.builtin.file:
    path: /etc/slurm-llnl
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'

- name: Distribuir configuración de Cgroups
  ansible.builtin.template:
    src: cgroup.conf.j2
    dest: /etc/slurm-llnl/cgroup.conf
    owner: slurm
    group: slurm
    mode: '0644'
  notify: Reiniciar slurmd
  tags:
    - cgroup_config

- name: Iniciar servicio Slurmd (Worker Daemon)
  ansible.builtin.service:
    name: slurmd
    state: started
    enabled: yes
  tags:
    - start_slurmd
