---
# ===== Tareas comunes para todos los hosts =====

- name: Configurar hostname del nodo
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  register: hostname_changed
  tags:
    - hostname

- name: Configurar archivo '/etc/hosts'
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'
  tags:
    - hosts_file

- name: Crear grupos del sistema
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: present
  loop:
    - { name: 'munge' }
    - { name: 'slurm' }
  tags:
    - system_users

- name: Crear usuarios del sistema
  ansible.builtin.user:
    name: "{{ item.name }}"
    group: "{{ item.name }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
    create_home: no
    system: yes
    state: present
  loop:
    - { name: 'munge', shell: '/usr/sbin/nologin', home: '/var/lib/munge' }
    - { name: 'slurm', shell: '/bin/bash', home: '/var/lib/slurm' }
  tags:
    - system_users

- name: Actualizar cache de apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - packages

- name: Extender la partición root para ocupar todo el disco
  ansible.builtin.command: growpart /dev/vda 2
  ignore_errors: yes # Ignora error si ya está extendida
  register: growpart_result
  changed_when: "'CHANGED' in growpart_result.stdout"
  tags:
    - disco 

- name: Redimensionar el sistema de archivos ext4
  ansible.builtin.command: resize2fs /dev/vda2
  when: growpart_result.changed
  tags:
    - disco

- name: Instalar paquetes comunes
  ansible.builtin.apt:
    name:
      - chrony
      - sssd
      - sssd-ldap
      - ldap-utils
      - acl
      - munge
      - slurm-wlm
      - nftables
      - nfs-common
      - prometheus-node-exporter
    state: present
  tags:
    - packages

- name: Crear directorios de Munge
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: munge
    group: munge
    mode: '0700'
  loop:
    - /etc/munge
    - /var/log/munge
    - /var/lib/munge
  tags:
    - directories

- name: Crear directorios de Slurm
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: slurm
    group: slurm
    mode: '0755'
  loop:
    - /var/log/slurm-llnl
    - /var/lib/slurm-llnl
    - /var/lib/slurm/slurmd
    - /var/lib/slurm/slurmctld
    - /etc/slurm-llnl
  tags:
    - directories

- name: Distribuir archivo slurm.conf
  ansible.builtin.template:
    src: slurm.conf.j2
    dest: /etc/slurm-llnl/slurm.conf
    owner: slurm
    group: slurm
    mode: '0644'
  tags:
    - slurm_config

- name: Detener munge inicialmente
  ansible.builtin.service:
    name: munge
    state: stopped
    enabled: yes
  tags:
    - munge_init
