---
# ===== Cliente NFS (Workers) =====

- name: Crear puntos de montaje locales
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - /nfs/general
    - /nfs/privileged
  tags:
    - mount_points

- name: Montar directorios NFS desde el Headnode
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "{{ hostvars[groups['headnode'][0]]['ansible_host'] }}:{{ item.src }}"
    fstype: nfs
    opts: rw,sync,hard,intr
    state: mounted
  loop:
    - { path: '/home', src: '/home' }
    - { path: '/nfs/general', src: '/nfs/general' }
    - { path: '/nfs/privileged', src: '/nfs/privileged' }
